version: "3.8"
services: 
  frontend:
    container_name: frontend
    build:
      context: . #if your Dockerfile is not at the same level change the path here (./frontend)
      target: dev
    #restart: always
    command: yarn dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://mystrapi:1337
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
networks:
  default:
    name: dev
    external: true
