version: "3"
services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    hostname: pfadimh-site-postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
